name: KKK
favicon: null
layout_spectrum: 0.4101783
typography_spectrum: 0.5842717
title: KRIS - KAT - KAYLEE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9270662
  lightness: 0.4358896
  saturation: 0.9844669
  rhythmicContrast: 0.8220947
purpose: []
