layout_spectrum: 0.4101783
typography_spectrum: 0.5842717
color:
  saturation: 0.9844669
  lightness: 0.4358896
  brandStrength: 0.9270662
  rhythmicContrast: 0.8220947
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: KKKkids
